### ISSUE TITLE
warning on mac build `inline function 'fpconv_init' is not defined`

### ISSUE THREAD

**Issue by hughperkins** [mpx/lua-cjson#28]
https://travis-ci.org/hughperkins/clnn/builds/107115627#L497-L503
```
In file included from lua_cjson.c:47:
./fpconv.h:15:20: warning: inline function 'fpconv_init' is not defined [-Wundefined-inline]
extern inline void fpconv_init();
                   ^
lua_cjson.c:1367:5: note: used here
    fpconv_init();
    ^
1 warning generated.
```

**Comment by mpx** [comment]
Thanks for the bug report. I've fixed the warning under clang now.

**Comment by hughperkins** [comment]
thanks :-)

**Comment by isomerase** [comment]
I just got this error while running `luarocks install lua-cjson` in Ubuntu.

```
In file included from lua_cjson.c:47:0:
fpconv.h:15:20: warning: inline function ‘fpconv_init’ declared but never defined
 extern inline void fpconv_init();
```

This is on a fresh torch install. I'm following the install instructions [here](https://github.com/jcjohnson/fast-neural-style) and made it fine up to the step where I had to install `lua-cjson`

**Comment by Integralist** [comment]
I'm also seeing this error.

I have the following compiler installed...

```
Apple LLVM version 8.0.0 (clang-800.0.38)
```

When I `sudo luarocks install lua-cjson` I get the error still showing.

**Comment by Tieske** [comment]
running into this as well...

**Comment by tanyapx** [comment]
Hi , 
is there any work around for this?
